### ISSUE TITLE
Name Converter

### ISSUE THREAD

**Issue by Tweadock** [MatePocs/boardgame_recommendation#1]
I am trying to adopt some concepts of this into a movie recommender of mine and if I had a csv with the movie names instead, how would I get that to work with your Name Converter? I have tried many things and I just cant get it to work.

**Comment by MatePocs** [comment]
I would not use the NameConverter class, it was just a way for me to connect ID numbers (integers) to game titles (names). You could do the same thing with a dictionary. If you make your movie titles your keys, you don't need to bother with it at all, and you can just delete every line that refers to NameConverter.
